version: '3.8'
services:
  train-router:
    build: .
    container_name: test-train-router
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
    command: /entrypoint.sh test
    volumes:
      - ./coverage:/opt/coverage

  redis:
      image: "redis:alpine"
      ports:
        - "6379:6379"
  rabbitmq:
      image: "rabbitmq:3.9-management-alpine"
      ports:
        - "5672:5672"
        - "15672:15672"
      environment:
        - "RABBITMQ_DEFAULT_USER=admin"
        - "RABBITMQ_DEFAULT_PASS=admin"
        - "RABBITMQ_DEFAULT_VHOST=/"
        - "RABBITMQ_ERLANG_COOKIE=admin"
        - "RABBITMQ_NODENAME=rabbit"
